/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/card.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    FullPage: typeof import('./src/components/fullpage/full-page.vue')['default']
    FullPageItem: typeof import('./src/components/fullpage/full-page-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SisterFooter: typeof import('./src/components/sister-footer.vue')['default']
    SisterHeader: typeof import('./src/components/sister-header.vue')['default']
    SisterLocale: typeof import('./src/components/sister-locale.vue')['default']
    SisterLogo: typeof import('./src/components/sister-logo.vue')['default']
    SisterRoutes: typeof import('./src/components/sister-routes.vue')['default']
    SisterTheme: typeof import('./src/components/sister-theme.vue')['default']
    SisterTimeline: typeof import('./src/components/sister-timeline.vue')['default']
    TextUnderline: typeof import('./src/components/text-underline.vue')['default']
  }
}
