/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/card.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FullPage: typeof import('./src/components/fullpage/full-page.vue')['default']
    FullPageItem: typeof import('./src/components/fullpage/full-page-item.vue')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMineEmpty: typeof import('~icons/mine/empty')['default']
    LocaleDropdown: typeof import('./src/components/locale-dropdown.vue')['default']
    LocaleSelect: typeof import('./src/components/locale-select.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import('./src/components/theme.vue')['default']
  }
}
